version: '3'

services:
  django:
    build: .
    command: ./start_progect_with_celery.sh
    ports:
      - "8000:8000"
    depends_on:
      - redis


  redis:
    image: redis:latest
    environment:
      - TZ=Europe/Moscow
    ports:
      - "6379:6379"
